language: go
go:
 - 1.11.x
 - 1.17.x

sudo: false

services:
  - rabbitmq

# safelist branch to build
branches:
  only:
      - master

addons:
  apt:
    packages:
    - rabbitmq-server

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

script:
  - make jenkins

notifications:
  email:
  - bifer@alea-soluciones.com
