language: go
go:
 - 1.10.x
 - 1.11.x
 - master

sudo: false

services:
  - rabbitmq

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

script:
  - make jenkins

notifications:
  email:
  - bifer@alea-soluciones.com
