language: go
go:
 - 1.3
 - 1.4
 - tip

before_install:
  - go get github.com/streadway/amqp

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

script:
  - go build
  - go build examples/consumer/consumer.go
  - go build examples/publisher/publisher.go
  - go test -tags integration ./...