// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AMQPPublisher is an autogenerated mock type for the AMQPPublisher type
type AMQPPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: _a0, _a1, _a2
func (_m *AMQPPublisher) Publish(_a0 string, _a1 []byte, _a2 ...map[string]interface{}) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// PublishWithTTL provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *AMQPPublisher) PublishWithTTL(_a0 string, _a1 []byte, _a2 int, _a3 ...map[string]interface{}) {
	_va := make([]interface{}, len(_a3))
	for _i := range _a3 {
		_va[_i] = _a3[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1, _a2)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// NewAMQPPublisher creates a new instance of AMQPPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAMQPPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *AMQPPublisher {
	mock := &AMQPPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
